services:
  web:
    image: musicstore
    depends_on:
      - db
    restart: always
    environment: 
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/musicstore?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - app

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: musicstore
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app
  
networks:
  app:
