DROP TABLE IF EXISTS TEST;

CREATE TABLE IF NOT EXISTS Test (
	test_id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	test_name VARCHAR(255) NOT NULL
);

INSERT INTO Test (test_id, test_name) VALUES (test_id, 'moi');

	
	